# Generated by Django 2.2.2 on 2019-06-22 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreatePrescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.CharField(max_length=20000)),
                ('medications', models.CharField(max_length=10000)),
                ('patient', models.EmailField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='recharge_balance',
            name='recharge_card',
            field=models.IntegerField(default=0),
        ),
    ]
